/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas;

import rapifood.pruebas.TestModificarMesa;
import rapifood.pruebas.TestModificarMesero;
import rapifood.pruebas.TestModificarPedido;
import rapifood.pruebas.TestModificarProducto;
import rapifood.pruebas.TestModificarReserva;

/**
 *
 * @author Lucas
 */
public class AdministradorLogueado extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorLogueado
     */
    public AdministradorLogueado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbAgregarProducto = new javax.swing.JButton();
        jbAgregarMesero = new javax.swing.JButton();
        jbRealizarPedido = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jbAgregarReserva = new javax.swing.JButton();
        jbBorrarReserva = new javax.swing.JButton();
        jbBorrarMesero = new javax.swing.JButton();
        jbBorrarProducto = new javax.swing.JButton();
        jbCancelarPedido = new javax.swing.JButton();
        jbAgregarQuitar = new javax.swing.JButton();
        jbVentasXMesero = new javax.swing.JButton();
        jbPedidosXMesa = new javax.swing.JButton();
        jbReservasXFechas = new javax.swing.JButton();
        jbModificarReserva = new javax.swing.JButton();
        jbModificarProducto = new javax.swing.JButton();
        jbModificarMesero = new javax.swing.JButton();
        jbModificarPedido = new javax.swing.JButton();
        jbModificarMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setName("Vista de Administrador"); // NOI18N

        jbAgregarProducto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_flour_64.png"))); // NOI18N
        jbAgregarProducto.setText("Agregar producto");
        jbAgregarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbAgregarProducto.setIconTextGap(10);
        jbAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdmProductos(evt);
            }
        });
        jbAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarProductoActionPerformed(evt);
            }
        });

        jbAgregarMesero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAgregarMesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/icons8_food_service_64.png"))); // NOI18N
        jbAgregarMesero.setText("Agregar mesero");
        jbAgregarMesero.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbAgregarMesero.setIconTextGap(10);
        jbAgregarMesero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdmMeseros(evt);
            }
        });
        jbAgregarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarMeseroActionPerformed(evt);
            }
        });

        jbRealizarPedido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbRealizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_cash_64.png"))); // NOI18N
        jbRealizarPedido.setText("Realizar pedido");
        jbRealizarPedido.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbRealizarPedido.setIconTextGap(10);
        jbRealizarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdmPedidos(evt);
            }
        });
        jbRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRealizarPedidoActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_shutdown_64.png"))); // NOI18N
        jButton6.setText("Cerrar Sesion");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.setIconTextGap(10);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVolver(evt);
            }
        });

        jbAgregarReserva.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAgregarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_restaurant_table_64.png"))); // NOI18N
        jbAgregarReserva.setText("Realizar reserva");
        jbAgregarReserva.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbAgregarReserva.setIconTextGap(10);
        jbAgregarReserva.setMaximumSize(new java.awt.Dimension(333, 73));
        jbAgregarReserva.setMinimumSize(new java.awt.Dimension(333, 73));
        jbAgregarReserva.setPreferredSize(new java.awt.Dimension(333, 73));
        jbAgregarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAgregarReserva(evt);
            }
        });
        jbAgregarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarReservaActionPerformed(evt);
            }
        });

        jbBorrarReserva.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbBorrarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_restaurant_table_64N.png"))); // NOI18N
        jbBorrarReserva.setText("Borrar reserva");
        jbBorrarReserva.setIconTextGap(10);
        jbBorrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarReservaActionPerformed(evt);
            }
        });

        jbBorrarMesero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbBorrarMesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_food_service_64N.png"))); // NOI18N
        jbBorrarMesero.setText("Borrar mesero");
        jbBorrarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarMeseroActionPerformed(evt);
            }
        });

        jbBorrarProducto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbBorrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_flour_64 - copia.png"))); // NOI18N
        jbBorrarProducto.setText("Borrar producto");
        jbBorrarProducto.setMaximumSize(new java.awt.Dimension(361, 73));
        jbBorrarProducto.setMinimumSize(new java.awt.Dimension(361, 73));
        jbBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarProductoActionPerformed(evt);
            }
        });

        jbCancelarPedido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbCancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_cash_64N.png"))); // NOI18N
        jbCancelarPedido.setText("Cancelar pedido");
        jbCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarPedidoActionPerformed(evt);
            }
        });

        jbAgregarQuitar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAgregarQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_table_64.png"))); // NOI18N
        jbAgregarQuitar.setText("Agregar o quitar mesa");
        jbAgregarQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarQuitarActionPerformed(evt);
            }
        });

        jbVentasXMesero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbVentasXMesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_ticket_purchase_64.png"))); // NOI18N
        jbVentasXMesero.setText("Pedidos de cada mesero");
        jbVentasXMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVentasXMeseroActionPerformed(evt);
            }
        });

        jbPedidosXMesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbPedidosXMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_receipt_64.png"))); // NOI18N
        jbPedidosXMesa.setText("Pedidos y monto consumido por mesa");
        jbPedidosXMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidosXMesaActionPerformed(evt);
            }
        });

        jbReservasXFechas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbReservasXFechas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_calendar_64.png"))); // NOI18N
        jbReservasXFechas.setText("Reservas por fecha");
        jbReservasXFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReservasXFechasActionPerformed(evt);
            }
        });

        jbModificarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_pencil_drawing_32.png"))); // NOI18N
        jbModificarReserva.setToolTipText("Modificar Reserva");
        jbModificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarReservaActionPerformed(evt);
            }
        });

        jbModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_pencil_drawing_32.png"))); // NOI18N
        jbModificarProducto.setToolTipText("Modificar Producto");
        jbModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarProductoActionPerformed(evt);
            }
        });

        jbModificarMesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_pencil_drawing_32.png"))); // NOI18N
        jbModificarMesero.setToolTipText("Modificar Mesero");
        jbModificarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarMeseroActionPerformed(evt);
            }
        });

        jbModificarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_pencil_drawing_32.png"))); // NOI18N
        jbModificarPedido.setToolTipText("Modificar Pedido");
        jbModificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarPedidoActionPerformed(evt);
            }
        });

        jbModificarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/ADM/icons8_pencil_drawing_32.png"))); // NOI18N
        jbModificarMesa.setToolTipText("Modificar Mesa");
        jbModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbPedidosXMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbReservasXFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbAgregarMesero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                .addComponent(jbRealizarPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                .addComponent(jbAgregarProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                            .addComponent(jbAgregarQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbAgregarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbModificarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbModificarMesero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbModificarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbModificarMesa))
                            .addComponent(jbModificarReserva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbVentasXMesero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrarMesero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCancelarPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrarReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbAgregarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrarReserva, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbBorrarMesero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAgregarMesero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbAgregarQuitar)
                            .addComponent(jbVentasXMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbModificarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbModificarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbModificarMesero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbModificarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbModificarMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbPedidosXMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbReservasXFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarReserva(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAgregarReserva
        Calendario pruebaCalendar = new Calendario();
        this.setVisible(false);
        new SeleccionarMesa().setVisible(false);
        pruebaCalendar.setIsAgregar(true);
        pruebaCalendar.inicializar();
        pruebaCalendar.setVisible(true);
        pruebaCalendar.setTitle("Fecha de Reserva");
    }//GEN-LAST:event_jbAgregarReserva

    private void jbAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarProductoActionPerformed
        new AgregarProducto().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbAgregarProductoActionPerformed

    private void BtnAdmProductos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdmProductos

    }//GEN-LAST:event_BtnAdmProductos

    private void BtnAdmMeseros(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdmMeseros

    }//GEN-LAST:event_BtnAdmMeseros

    private void BtnAdmPedidos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdmPedidos
        
    }//GEN-LAST:event_BtnAdmPedidos

    private void BtnVolver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolver
       this.setVisible(false);
       new VAdminLogin().setVisible(true);
    }//GEN-LAST:event_BtnVolver

    private void jbAgregarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarReservaActionPerformed

    }//GEN-LAST:event_jbAgregarReservaActionPerformed

    private void jbBorrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarReservaActionPerformed
        Calendario pruebaCalendar = new Calendario();
        this.setVisible(false);
        new SeleccionarMesa().setVisible(false);
        pruebaCalendar.setIsAgregar(false);
        pruebaCalendar.inicializar();
        pruebaCalendar.setVisible(true);
        pruebaCalendar.setTitle("Buscar Reserva a Borrar");
    }//GEN-LAST:event_jbBorrarReservaActionPerformed

    private void jbAgregarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarMeseroActionPerformed
        this.setVisible(false);
        new AgregarMesero().setVisible(true);
    }//GEN-LAST:event_jbAgregarMeseroActionPerformed

    private void jbBorrarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarMeseroActionPerformed
        this.setVisible(false);
        new BorrarMesero().setVisible(true);
    }//GEN-LAST:event_jbBorrarMeseroActionPerformed

    private void jbBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarProductoActionPerformed
        this.setVisible(false);
        new BorrarProducto().setVisible(true);
    }//GEN-LAST:event_jbBorrarProductoActionPerformed

    private void jbRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRealizarPedidoActionPerformed
        this.setVisible(false);
        new AgregarPedido().setVisible(true);
    }//GEN-LAST:event_jbRealizarPedidoActionPerformed

    private void jbCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarPedidoActionPerformed
        this.setVisible(false);
        new BorrarPedido().setVisible(true);
    }//GEN-LAST:event_jbCancelarPedidoActionPerformed

    private void jbAgregarQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarQuitarActionPerformed
        this.setVisible(false);
        new AgregarBorrarMesa().setVisible(true);
    }//GEN-LAST:event_jbAgregarQuitarActionPerformed

    private void jbVentasXMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVentasXMeseroActionPerformed
        this.setVisible(false);
        new PedidosAtendidos().setVisible(true);
    }//GEN-LAST:event_jbVentasXMeseroActionPerformed

    private void jbPedidosXMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidosXMesaActionPerformed
        this.setVisible(false);
        new MontosXMesa().setVisible(true);
    }//GEN-LAST:event_jbPedidosXMesaActionPerformed

    private void jbReservasXFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReservasXFechasActionPerformed
        this.setVisible(false);
        new ReservaXFecha().setVisible(true);
    }//GEN-LAST:event_jbReservasXFechasActionPerformed

    private void jbModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarMesaActionPerformed
        this.setVisible(false);
        new TestModificarMesa().setVisible(true);
    }//GEN-LAST:event_jbModificarMesaActionPerformed

    private void jbModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarProductoActionPerformed
        this.setVisible(false);
        new TestModificarProducto().setVisible(true);
    }//GEN-LAST:event_jbModificarProductoActionPerformed

    private void jbModificarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarMeseroActionPerformed
        this.setVisible(false);
        new TestModificarMesero().setVisible(true);
    }//GEN-LAST:event_jbModificarMeseroActionPerformed

    private void jbModificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarReservaActionPerformed
        this.setVisible(false);
        new TestModificarReserva().setVisible(true);
    }//GEN-LAST:event_jbModificarReservaActionPerformed

    private void jbModificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarPedidoActionPerformed
        this.setVisible(false);
        new TestModificarPedido().setVisible(true);
    }//GEN-LAST:event_jbModificarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorLogueado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorLogueado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorLogueado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorLogueado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorLogueado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregarMesero;
    private javax.swing.JButton jbAgregarProducto;
    private javax.swing.JButton jbAgregarQuitar;
    private javax.swing.JButton jbAgregarReserva;
    private javax.swing.JButton jbBorrarMesero;
    private javax.swing.JButton jbBorrarProducto;
    private javax.swing.JButton jbBorrarReserva;
    private javax.swing.JButton jbCancelarPedido;
    private javax.swing.JButton jbModificarMesa;
    private javax.swing.JButton jbModificarMesero;
    private javax.swing.JButton jbModificarPedido;
    private javax.swing.JButton jbModificarProducto;
    private javax.swing.JButton jbModificarReserva;
    private javax.swing.JButton jbPedidosXMesa;
    private javax.swing.JButton jbRealizarPedido;
    private javax.swing.JButton jbReservasXFechas;
    private javax.swing.JButton jbVentasXMesero;
    // End of variables declaration//GEN-END:variables
}
