/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas;

import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import rapifood.modelo.Conexion;
import rapifood.modelo.Mesa;
import rapifood.modelo.MesaData;

/**
 *
 * @author Fedep
 */
public class AgregarBorrarMesa extends javax.swing.JFrame {

    private final Conexion con;
    private final MesaData mesaData;
    
    /**
     * Creates new form AgregarQuitarMesa
     */
    public AgregarBorrarMesa() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = new Conexion();
        mesaData = new MesaData(con); 
        JButton[] arrBotones = {jbMesa1,jbMesa2,jbMesa3,jbMesa4,jbMesa5,jbMesa6,jbMesa7,jbMesa8,jbMesa9,jbMesa10,jbMesa11,jbMesa12,jbMesa13,jbMesa14,jbMesa15};
        List<Mesa> mesasDisponibles = mesaData.obtenerMesas();
        for(Mesa mesa : mesasDisponibles){
            if(!mesa.isEstado()){
                arrBotones[mesa.getId()-1].setIcon(new ImageIcon(getClass().getResource("../../RSC/MesasIconos/MesaN"+(mesa.getId())+".png")));
            }
            else{
                arrBotones[mesa.getId()-1].setIcon(new ImageIcon(getClass().getResource("../../RSC/MesasIconos/MesaS"+(mesa.getId())+".png")));
            }
        }
    }
    
    private void agregarQuitarMesa(JButton boton){
        if(mesaData.buscarMesa(Integer.parseInt(boton.getName())).isEstado()){
            boton.setIcon(new ImageIcon(getClass().getResource("../../RSC/MesasIconos/MesaN"+(boton.getName())+".png")));
            Mesa mesa = mesaData.buscarMesa(Integer.parseInt(boton.getName()));
            mesa.setEstado(false);
            mesaData.actualizarMesa(mesa);
        }
        else{
            boton.setIcon(new ImageIcon(getClass().getResource("../../RSC/MesasIconos/MesaS"+(boton.getName())+".png")));
            Mesa mesa = mesaData.buscarMesa(Integer.parseInt(boton.getName()));
            mesa.setEstado(true);
            mesaData.actualizarMesa(mesa);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMesa11 = new javax.swing.JButton();
        jbMesa6 = new javax.swing.JButton();
        jbMesa14 = new javax.swing.JButton();
        jbMesa12 = new javax.swing.JButton();
        jbMesa15 = new javax.swing.JButton();
        jbMesa13 = new javax.swing.JButton();
        jbMesa2 = new javax.swing.JButton();
        jbMesa1 = new javax.swing.JButton();
        jbMesa4 = new javax.swing.JButton();
        jbMesa5 = new javax.swing.JButton();
        jbMesa3 = new javax.swing.JButton();
        jbMesa8 = new javax.swing.JButton();
        jbMesa10 = new javax.swing.JButton();
        jbMesa9 = new javax.swing.JButton();
        jbMesa7 = new javax.swing.JButton();
        jbBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar o Borrar Mesas");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN11.png"))); // NOI18N
        jbMesa11.setToolTipText("Cambiar estado de mesa 11");
        jbMesa11.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa11.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa11.setName("11"); // NOI18N
        jbMesa11.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa11ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 348, 110, 110));

        jbMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN6.png"))); // NOI18N
        jbMesa6.setToolTipText("Cambiar estado de mesa 6");
        jbMesa6.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa6.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa6.setName("6"); // NOI18N
        jbMesa6.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, 110, 110));

        jbMesa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN14.png"))); // NOI18N
        jbMesa14.setToolTipText("Cambiar estado de mesa 14");
        jbMesa14.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa14.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa14.setName("14"); // NOI18N
        jbMesa14.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa14ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa14, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 348, 110, 110));

        jbMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN12.png"))); // NOI18N
        jbMesa12.setToolTipText("Cambiar estado de mesa 12");
        jbMesa12.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa12.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa12.setName("12"); // NOI18N
        jbMesa12.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa12ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 348, 110, 110));

        jbMesa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN15.png"))); // NOI18N
        jbMesa15.setToolTipText("Cambiar estado de mesa 15");
        jbMesa15.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa15.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa15.setName("15"); // NOI18N
        jbMesa15.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa15ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa15, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 348, 110, 110));

        jbMesa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN13.png"))); // NOI18N
        jbMesa13.setToolTipText("Cambiar estado de mesa 13");
        jbMesa13.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa13.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa13.setName("13"); // NOI18N
        jbMesa13.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa13ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa13, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 348, 110, 110));

        jbMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN2.png"))); // NOI18N
        jbMesa2.setToolTipText("Cambiar estado de mesa 2");
        jbMesa2.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa2.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa2.setName("2"); // NOI18N
        jbMesa2.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 92, 110, 110));

        jbMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN1.png"))); // NOI18N
        jbMesa1.setToolTipText("Cambiar estado de mesa 1");
        jbMesa1.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa1.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa1.setName("1"); // NOI18N
        jbMesa1.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 92, 110, 110));

        jbMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN4.png"))); // NOI18N
        jbMesa4.setToolTipText("Cambiar estado de mesa 4");
        jbMesa4.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa4.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa4.setName("4"); // NOI18N
        jbMesa4.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 92, 110, 110));

        jbMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN5.png"))); // NOI18N
        jbMesa5.setToolTipText("Cambiar estado de mesa 5");
        jbMesa5.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa5.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa5.setName("5"); // NOI18N
        jbMesa5.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 92, 110, 110));

        jbMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN3.png"))); // NOI18N
        jbMesa3.setToolTipText("Cambiar estado de mesa 3");
        jbMesa3.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa3.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa3.setName("3"); // NOI18N
        jbMesa3.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 92, 110, 110));

        jbMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN8.png"))); // NOI18N
        jbMesa8.setToolTipText("Cambiar estado de mesa 8");
        jbMesa8.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa8.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa8.setName("8"); // NOI18N
        jbMesa8.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 220, 110, 110));

        jbMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN10.png"))); // NOI18N
        jbMesa10.setToolTipText("Cambiar estado de mesa 10");
        jbMesa10.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa10.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa10.setName("10"); // NOI18N
        jbMesa10.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa10ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 220, 110, 110));

        jbMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN9.png"))); // NOI18N
        jbMesa9.setToolTipText("Cambiar estado de mesa 9");
        jbMesa9.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa9.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa9.setName("9"); // NOI18N
        jbMesa9.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 220, 110, 110));

        jbMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaN7.png"))); // NOI18N
        jbMesa7.setToolTipText("Cambiar estado de mesa 7");
        jbMesa7.setMaximumSize(new java.awt.Dimension(200, 204));
        jbMesa7.setMinimumSize(new java.awt.Dimension(200, 204));
        jbMesa7.setName("7"); // NOI18N
        jbMesa7.setPreferredSize(new java.awt.Dimension(204, 200));
        jbMesa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 220, 110, 110));

        jbBack.setText("Volver al menu");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaON (1).jpg"))); // NOI18N
        jLabel2.setText("Mesa Disponible");
        jLabel2.setToolTipText("Haga click en cualquier mesa para cambiar su estado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RSC/MesasIconos/MesaOff.jpg"))); // NOI18N
        jLabel1.setText("Mesa NO Disponible");
        jLabel1.setToolTipText("Haga click en cualquier mesa para cambiar su estado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 11, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMesa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa11ActionPerformed
        agregarQuitarMesa(jbMesa11);
    }//GEN-LAST:event_jbMesa11ActionPerformed

    private void jbMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa6ActionPerformed
        agregarQuitarMesa(jbMesa6);
    }//GEN-LAST:event_jbMesa6ActionPerformed

    private void jbMesa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa14ActionPerformed
        agregarQuitarMesa(jbMesa14);
    }//GEN-LAST:event_jbMesa14ActionPerformed

    private void jbMesa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa12ActionPerformed
        agregarQuitarMesa(jbMesa12);
    }//GEN-LAST:event_jbMesa12ActionPerformed

    private void jbMesa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa15ActionPerformed
        agregarQuitarMesa(jbMesa15);
    }//GEN-LAST:event_jbMesa15ActionPerformed

    private void jbMesa13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa13ActionPerformed
        agregarQuitarMesa(jbMesa13);
    }//GEN-LAST:event_jbMesa13ActionPerformed

    private void jbMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa2ActionPerformed
        agregarQuitarMesa(jbMesa2);
    }//GEN-LAST:event_jbMesa2ActionPerformed

    private void jbMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa1ActionPerformed
        agregarQuitarMesa(jbMesa1);
    }//GEN-LAST:event_jbMesa1ActionPerformed

    private void jbMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa4ActionPerformed
        agregarQuitarMesa(jbMesa4);
    }//GEN-LAST:event_jbMesa4ActionPerformed

    private void jbMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa5ActionPerformed
        agregarQuitarMesa(jbMesa5);
    }//GEN-LAST:event_jbMesa5ActionPerformed

    private void jbMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa3ActionPerformed
        agregarQuitarMesa(jbMesa3);
    }//GEN-LAST:event_jbMesa3ActionPerformed

    private void jbMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa8ActionPerformed
        agregarQuitarMesa(jbMesa8);
    }//GEN-LAST:event_jbMesa8ActionPerformed

    private void jbMesa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa10ActionPerformed
        agregarQuitarMesa(jbMesa10);
    }//GEN-LAST:event_jbMesa10ActionPerformed

    private void jbMesa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa9ActionPerformed
        agregarQuitarMesa(jbMesa9);
    }//GEN-LAST:event_jbMesa9ActionPerformed

    private void jbMesa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa7ActionPerformed
        agregarQuitarMesa(jbMesa7);
    }//GEN-LAST:event_jbMesa7ActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        this.setVisible(false);
        new AdministradorLogueado().setVisible(true);
    }//GEN-LAST:event_jbBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarBorrarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarBorrarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarBorrarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarBorrarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarBorrarMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbMesa1;
    private javax.swing.JButton jbMesa10;
    private javax.swing.JButton jbMesa11;
    private javax.swing.JButton jbMesa12;
    private javax.swing.JButton jbMesa13;
    private javax.swing.JButton jbMesa14;
    private javax.swing.JButton jbMesa15;
    private javax.swing.JButton jbMesa2;
    private javax.swing.JButton jbMesa3;
    private javax.swing.JButton jbMesa4;
    private javax.swing.JButton jbMesa5;
    private javax.swing.JButton jbMesa6;
    private javax.swing.JButton jbMesa7;
    private javax.swing.JButton jbMesa8;
    private javax.swing.JButton jbMesa9;
    // End of variables declaration//GEN-END:variables
}
