/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas;

import javax.swing.JOptionPane;
import rapifood.modelo.Conexion;
import rapifood.modelo.Producto;
import rapifood.modelo.ProductoData;

/**
 *
 * @author Fedep
 */
public class AgregarProducto extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProducto
     */
    
    private Conexion con;
    private ProductoData productoData;
    private int idAModificar;
    private boolean isModificar;

    public void setIdAModificar(int idAModificar) {
        this.idAModificar = idAModificar;
    }

    public void setIsModificar(boolean isModificar) {
        this.isModificar = isModificar;
    }
    
    public AgregarProducto() {
        initComponents();
        inicializarComponentes();
        this.setLocationRelativeTo(null);
    }
    
    private void inicializarComponentes(){
        con = new Conexion();
        productoData = new ProductoData(con);
        isModificar = false;
    }
    
    private boolean controlCampos(){
        boolean control_nombre=false, control_precio=false,retorno=false;
        if(tfNombre.getText().equals("")){
            control_nombre=true;
        }
        if(tfPrecio.getText().equals("")){
            control_precio=true;
        }
        if(control_nombre && control_precio){
            JOptionPane.showMessageDialog(this, "Ingrese nombre y precio");
        }
        else if(control_nombre && !control_precio){
            JOptionPane.showMessageDialog(this, "Ingrese nombre");
        }
        else if(!control_nombre && control_precio){
            JOptionPane.showMessageDialog(this, "Ingrese precio");
        }
        else{
            retorno=true;
        }
        return retorno; 
    }
    
    private boolean productoYaIngresado(){
        boolean retorno=false;
        for(Producto producto : productoData.obtenerProductosActivos()){
            if(producto.getNombre().equals(tfNombre.getText())){
                retorno=true;
            }
        }
        return retorno;
    }
    
    private boolean precioNegativo(){
        boolean retorno=false;
        if(Double.parseDouble(tfPrecio.getText())<0){
            retorno=true;
        }
        return retorno;
    }

    private void volverAlMenu(){
        this.setVisible(false);
        new AdministradorLogueado().setVisible(true);
    }
    
    private boolean controlCamposCorrectos(){
        boolean controlNombre=false,controlPrecio=false,retorno=false;
        if(controlCampos()){
            if(productoYaIngresado()){
                controlNombre = true;
            }
            else if(precioNegativo()){
                controlPrecio = true;
            }
            if(controlNombre && controlPrecio){
                JOptionPane.showMessageDialog(this, "El nombre ingresado ya se encuentra registrado y el precio es negativo.");
                tfNombre.setText("");
                tfPrecio.setText("");
            }
            else if(controlNombre && !controlPrecio){
                JOptionPane.showMessageDialog(this, "Ya hay ingresado un producto con dicho nombre.");
                tfNombre.setText("");
            }
            else if(!controlNombre && controlPrecio){
                JOptionPane.showMessageDialog(this, "Ingrese un precio coherente.");
                tfPrecio.setText("");
            }
            else{
                retorno=true;
            }
        }
        return retorno;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jlPrecio = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        jbAgregar = new javax.swing.JButton();
        jbBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Producto");
        setResizable(false);

        jlNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlNombre.setText("Nombre del producto:");

        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });

        jlPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlPrecio.setText("Precio: ");

        tfPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecioKeyTyped(evt);
            }
        });

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbBack.setText("Volver al menu");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNombre)
                                    .addComponent(jlPrecio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNombre)
                                    .addComponent(tfPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPrecio)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlNombre)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbAgregar)
                .addGap(18, 18, 18)
                .addComponent(jbBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras.");
        }
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecioKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros.");
        }
    }//GEN-LAST:event_tfPrecioKeyTyped

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        if(isModificar){
            if(productoData.buscarProducto(idAModificar).getNombre().equals(tfNombre.getText())){
                if(controlCampos()){
                    if(precioNegativo()){
                        JOptionPane.showMessageDialog(this, "Ingrese un precio coherente.");
                        tfPrecio.setText("");
                    }
                    else{
                        Producto producto = new Producto(idAModificar,tfNombre.getText(),Double.parseDouble(tfPrecio.getText()),true);
                        productoData.actualizarProducto(producto);
                        JOptionPane.showMessageDialog(this, "Producto modificado correctamente.");
                        volverAlMenu(); 
                    }
                }
            }
            else{
                if(controlCamposCorrectos()){
                    Producto producto = new Producto(idAModificar,tfNombre.getText(),Double.parseDouble(tfPrecio.getText()),true);
                    productoData.actualizarProducto(producto);
                    JOptionPane.showMessageDialog(this, "Producto modificado correctamente.");
                    volverAlMenu();
                    }
                }
            }
        else{
            if(controlCamposCorrectos()){
               Producto producto = new Producto(tfNombre.getText(),Double.parseDouble(tfPrecio.getText()),true);
                productoData.guardarProducto(producto);
                JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");
                volverAlMenu(); 
            }
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        volverAlMenu();
    }//GEN-LAST:event_jbBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBack;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
