/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas;

import java.util.Calendar;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Fedep
 */
public class HorariosDisponibles extends javax.swing.JFrame {

    /**
     * Creates new form AdmHorarios
     */
    
    private Calendar fechaElegida;
    private boolean isModificar;
    private int idAModificar;
    
    public HorariosDisponibles() {
        initComponents();
        this.setLocationRelativeTo(null);
        isModificar=false;
    }
    
    public void setFechaElegida(Calendar fechaElegida){
        this.fechaElegida = fechaElegida;
    }

    public void setIsModificar(boolean isModificar) {
        this.isModificar = isModificar;
    }

    public void setIdAModificar(int idAModificar) {
        this.idAModificar = idAModificar;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgHorarios = new javax.swing.ButtonGroup();
        rb12 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rb11 = new javax.swing.JRadioButton();
        jbAceptar = new javax.swing.JButton();
        rb9 = new javax.swing.JRadioButton();
        jlMañana = new javax.swing.JLabel();
        rb17 = new javax.swing.JRadioButton();
        rb18 = new javax.swing.JRadioButton();
        rb19 = new javax.swing.JRadioButton();
        rb20 = new javax.swing.JRadioButton();
        jlTarde = new javax.swing.JLabel();
        jlHorarios = new javax.swing.JLabel();
        jbBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Horario de Reserva");
        setResizable(false);

        bgHorarios.add(rb12);
        rb12.setText("12:00 - 13:00");
        rb12.setName("12"); // NOI18N

        bgHorarios.add(rb10);
        rb10.setText("10:00 - 11:00");
        rb10.setName("10"); // NOI18N

        bgHorarios.add(rb11);
        rb11.setText("11:00 - 12:00");
        rb11.setName("11"); // NOI18N

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        bgHorarios.add(rb9);
        rb9.setText("09:00 - 10:00");
        rb9.setName("9"); // NOI18N

        jlMañana.setText("TURNO MAÑANA");

        bgHorarios.add(rb17);
        rb17.setText("17:00 - 18:00");
        rb17.setName("17"); // NOI18N

        bgHorarios.add(rb18);
        rb18.setText("18:00 - 19:00");
        rb18.setName("18"); // NOI18N

        bgHorarios.add(rb19);
        rb19.setText("19:00 - 20:00");
        rb19.setName("19"); // NOI18N

        bgHorarios.add(rb20);
        rb20.setText("20:00 - 21:00");
        rb20.setName("20"); // NOI18N

        jlTarde.setText("TURNO TARDE");

        jlHorarios.setText("HORARIOS DISPONIBLES");

        jbBack.setText("Volver al menu");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione el horario de su reserva:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rb20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rb11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rb19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rb10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rb18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlMañana)
                                            .addComponent(rb9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rb17)
                                            .addComponent(jlTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jlHorarios)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jlHorarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMañana)
                    .addComponent(jlTarde))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb9)
                    .addComponent(rb17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb10)
                    .addComponent(rb18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb11)
                    .addComponent(rb19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb12)
                    .addComponent(rb20))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        SeleccionarMesa aM = new SeleccionarMesa();
        if(isModificar){
            if(bgHorarios.getSelection() == null){
                JOptionPane.showMessageDialog(this, "Ingrese un horario.");
            }
            else{
                for (Enumeration<AbstractButton> buttons = bgHorarios.getElements(); buttons.hasMoreElements();) { 
                    AbstractButton button = buttons.nextElement(); 
                    if (button.isSelected()){ 
                        fechaElegida.set(Calendar.HOUR, Integer.parseInt(button.getName()));
                        fechaElegida.set(Calendar.HOUR_OF_DAY, Integer.parseInt(button.getName()));
                        System.out.println(fechaElegida);
                    } 
                }
                aM.setFechaElegida(fechaElegida);
                aM.setIsModificar(true);
                aM.setIdAModificar(idAModificar);
                aM.inicializar();
                this.setVisible(false);
                aM.setVisible(true);
            }
        }
        else{
            if(bgHorarios.getSelection() == null){
                JOptionPane.showMessageDialog(this, "Ingrese un horario.");
            }
            else{
                for (Enumeration<AbstractButton> buttons = bgHorarios.getElements(); buttons.hasMoreElements();) { 
                    AbstractButton button = buttons.nextElement(); 
                    if (button.isSelected()){ 
                        fechaElegida.set(Calendar.HOUR, Integer.parseInt(button.getName()));
                        fechaElegida.set(Calendar.HOUR_OF_DAY, Integer.parseInt(button.getName()));
                    } 
                }
                aM.setFechaElegida(fechaElegida);
                aM.inicializar();
                this.setVisible(false);
                aM.setVisible(true);
            }         
        }
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        this.setVisible(false);
        new AdministradorLogueado().setVisible(true);
    }//GEN-LAST:event_jbBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorariosDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorariosDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorariosDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorariosDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HorariosDisponibles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgHorarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbBack;
    private javax.swing.JLabel jlHorarios;
    private javax.swing.JLabel jlMañana;
    private javax.swing.JLabel jlTarde;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb17;
    private javax.swing.JRadioButton rb18;
    private javax.swing.JRadioButton rb19;
    private javax.swing.JRadioButton rb20;
    private javax.swing.JRadioButton rb9;
    // End of variables declaration//GEN-END:variables
}
