/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas;

import java.sql.Timestamp;
import java.util.Calendar;
import javax.swing.JOptionPane;
import rapifood.modelo.Conexion;
import rapifood.modelo.Mesa;
import rapifood.modelo.MesaData;
import rapifood.modelo.ReservaData;
import rapifood.modelo.Reserva;

/**
 *
 * @author Fedep
 */
public class IngresoComensal extends javax.swing.JFrame {

    private Calendar fechaElegida;
    private MesaData mesaData;
    private int id_mesa;
    private ReservaData reservaData;
    private Conexion con;
    private boolean isModificar;
    private int idAModificar;
    
    /**
     * Creates new form PruebaIngreso
     */
    public IngresoComensal() {
        initComponents();
        inicializarComponentes();
        this.setLocationRelativeTo(null);
    }
    
    private void inicializarComponentes(){
        con = new Conexion();
        reservaData = new ReservaData(con);
        mesaData = new MesaData(con);
        isModificar=false;
    }

    public void setIsModificar(boolean isModificar) {
        this.isModificar = isModificar;
    }

    public void setIdAModificar(int idAModificar) {
        this.idAModificar = idAModificar;
    }
    
    public void inicializar(){
        for(int i=0;i<mesaData.buscarMesa(id_mesa).getMax_comensales();i++){
            cbComensales.addItem(String.valueOf(i+1));
        }
    }

    public void setFechaElegida(Calendar fechaElegida) {
        this.fechaElegida = fechaElegida;
    }

    public void setId_mesa(int id_mesa) {
        this.id_mesa = id_mesa;
    }
    
    private boolean controlCampos(){
        boolean control_nombre=false, control_apellido=false,retorno=false;
        if(tfNombre.getText().equals("")){
            control_nombre=true;
        }
        if(tfApellido.getText().equals("")){
            control_apellido=true;
        }
        if(control_nombre && control_apellido){
            JOptionPane.showMessageDialog(this, "Ingrese nombre y apellido.");
        }
        else if(control_nombre && !control_apellido){
            JOptionPane.showMessageDialog(this, "Ingrese nombre");
        }
        else if(!control_nombre && control_apellido){
            JOptionPane.showMessageDialog(this, "Ingrese apellido");
        }
        else{
            retorno=true;
        }
        return retorno;
    }
    
    private void volverAlMenu(){
        new AdministradorLogueado().setVisible(true);
        this.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        jlComensales = new javax.swing.JLabel();
        cbComensales = new javax.swing.JComboBox<>();
        jbAceptar = new javax.swing.JButton();
        jbBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos de reservacion");
        setResizable(false);

        jlNombre.setText("Nombre");

        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });

        jLabel1.setText("Apellido");

        tfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidoKeyTyped(evt);
            }
        });

        jlComensales.setText("Numero de comensales");

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbBack.setText("Regresar al menu");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jlComensales)
                        .addGap(18, 18, 18)
                        .addComponent(cbComensales, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlNombre)
                        .addContainerGap(361, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbBack)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlComensales)
                    .addComponent(cbComensales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        if(isModificar){
            if(controlCampos()){
            Timestamp fechaReservada = new Timestamp(fechaElegida.getTimeInMillis());
            Mesa mesa = mesaData.buscarMesa(id_mesa);
            Reserva reserva = new Reserva(idAModificar,tfNombre.getText(),tfApellido.getText(),fechaReservada,true,mesa,Integer.parseInt(cbComensales.getSelectedItem().toString()));
            reservaData.actualizarReserva(reserva);
            JOptionPane.showMessageDialog(this, "Reserva modificada correctamente.");
            volverAlMenu();
            }
        }
        else{
            if(controlCampos()){
                Timestamp fechaReservada = new Timestamp(fechaElegida.getTimeInMillis());
                Mesa mesa = mesaData.buscarMesa(id_mesa);
                Reserva reserva = new Reserva(tfNombre.getText(),tfApellido.getText(),fechaReservada,true,mesa,Integer.parseInt(cbComensales.getSelectedItem().toString()));
                reservaData.guardarReserva(reserva);
                JOptionPane.showMessageDialog(this, "Reserva hecha correctamente.");
                volverAlMenu();
            } 
        }

    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        volverAlMenu();
    }//GEN-LAST:event_jbBackActionPerformed

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras.");
        }
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras.");
        }
    }//GEN-LAST:event_tfApellidoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoComensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoComensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoComensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoComensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoComensal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbComensales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbBack;
    private javax.swing.JLabel jlComensales;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
