/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rapifood.modelo.Conexion;
import rapifood.modelo.DetallePedido;
import rapifood.modelo.DetallePedidoData;
import rapifood.modelo.Mesa;
import rapifood.modelo.MesaData;
import rapifood.modelo.Pedido;
import rapifood.modelo.PedidoData;
import rapifood.modelo.Producto;

/**
 *
 * @author Fedep
 */
public class MontosXMesa extends javax.swing.JFrame {
    
    private Conexion con;
    private PedidoData pedidoData;
    private DetallePedidoData detallePedidoData;
    private MesaData mesaData;
    private DefaultTableModel modeloPedidos;
    private DefaultTableModel modeloProductos;
    private DefaultTableModel modeloMesas;
    private List<DetallePedido> detalles;

    /**
     * Creates new form MontosXMesa
     */
    public MontosXMesa() {
        initComponents();
        inicializarComponentes();
        this.setLocationRelativeTo(null);
    }
    
    private void inicializarComponentes(){
        con = new Conexion();
        
        pedidoData = new PedidoData(con);
        detallePedidoData = new DetallePedidoData(con);
        mesaData = new MesaData(con);
        
        modeloPedidos = (DefaultTableModel) jtPedidos.getModel();
        modeloProductos = (DefaultTableModel) jtProductos.getModel();
        modeloMesas = (DefaultTableModel) jtMesas.getModel();
        
        detalles = detallePedidoData.obtenerDetallesPedidos();
        setearInvisible(true);
    }
    
    private void setearInvisible(boolean bool){
        if(bool){
            jlPedidosFecha.setVisible(false);
            jlFecha.setVisible(false);
            jlProducto.setVisible(false);
            jlMontoConsumido.setVisible(false);
        }
        else{
            jlPedidosFecha.setVisible(true);
            jlFecha.setVisible(true);
            jlProducto.setVisible(true);
            jlMontoConsumido.setVisible(true);
        }
    }
    
    private void limpiarTabla(JTable tabla){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    
    private void cargarPedidos(){
        limpiarTabla(jtPedidos);
        for(Pedido pedido : pedidoData.obtenerPedidosActivos()){
            if(dcFechaElegida.getDate().equals(pedido.getFechaPedido())){
                modeloPedidos.addRow(new Object[]{pedido.getId(),pedido.getMesa().getId(),pedido.getMesero().getNombre(),pedido.getMonto()});
            }
        }
    }
    
    private void cargarProductos(){
        limpiarTabla(jtProductos);
        List<Producto> productos = new ArrayList<>();
        for(DetallePedido detalle : detalles){
            if(Integer.parseInt(jtPedidos.getValueAt(jtPedidos.getSelectedRow(), 0).toString()) == detalle.getPedido().getId()){
                productos.add(detalle.getProducto());
            }
        }
        int cont=1;
        for(Producto producto : productos){
            modeloProductos.addRow(new Object[]{cont,producto.getNombre(),producto.getPrecio()});
            cont++;
        }
    }
    
    private void cargarMesas(){
        limpiarTabla(jtMesas);
        for(Mesa mesa : mesaData.obtenerMesas()){
            double total=0;
            for(int i=0;i<jtPedidos.getRowCount();i++){
                if(Integer.parseInt(jtPedidos.getValueAt(i, 1).toString()) == mesa.getId()){
                    total+=Double.parseDouble(jtPedidos.getValueAt(i, 3).toString());
                }
            }
            modeloMesas.addRow(new Object[]{mesa.getId(),total});
        }
    }
    
    private void cargarTablas(){
        limpiarTabla(jtProductos);
        cargarPedidos();
        cargarMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSeleccionFecha = new javax.swing.JLabel();
        dcFechaElegida = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jlPedidosFecha = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jlProducto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtMesas = new javax.swing.JTable();
        jlMontoConsumido = new javax.swing.JLabel();
        jbAceptar = new javax.swing.JButton();
        jbBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Montos/Pedidos por Mesa");
        setResizable(false);

        jlSeleccionFecha.setText("Seleccione una fecha: ");

        dcFechaElegida.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                dcFechaElegidaComponentAdded(evt);
            }
        });
        dcFechaElegida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcFechaElegidaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dcFechaElegidaMousePressed(evt);
            }
        });
        dcFechaElegida.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dcFechaElegidaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        dcFechaElegida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcFechaElegidaPropertyChange(evt);
            }
        });

        jtPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mesa", "Mesero", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPedidos);

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtProductos);

        jlPedidosFecha.setText("Pedidos de la fecha: ");

        jlFecha.setText("Fecha");

        jlProducto.setText("Productos");

        jtMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtMesas);

        jlMontoConsumido.setText("Monto consumido por mesa");

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbBack.setText("Volver al menu");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlPedidosFecha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlFecha))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlSeleccionFecha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dcFechaElegida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbAceptar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlProducto)
                                        .addGap(129, 129, 129))))
                            .addComponent(jlMontoConsumido))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcFechaElegida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSeleccionFecha)
                            .addComponent(jbAceptar))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPedidosFecha)
                            .addComponent(jlFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlMontoConsumido)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBack)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dcFechaElegidaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dcFechaElegidaInputMethodTextChanged
        
    }//GEN-LAST:event_dcFechaElegidaInputMethodTextChanged

    private void dcFechaElegidaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_dcFechaElegidaComponentAdded
        
    }//GEN-LAST:event_dcFechaElegidaComponentAdded

    private void dcFechaElegidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcFechaElegidaMouseClicked
       
    }//GEN-LAST:event_dcFechaElegidaMouseClicked

    private void dcFechaElegidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcFechaElegidaMousePressed
        
    }//GEN-LAST:event_dcFechaElegidaMousePressed

    private void dcFechaElegidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcFechaElegidaPropertyChange

    }//GEN-LAST:event_dcFechaElegidaPropertyChange

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        if(dcFechaElegida.getDate()==null){
            JOptionPane.showMessageDialog(this, "Ingrese una fecha.");
        }
        else{
            setearInvisible(false);
            jlFecha.setText(dcFechaElegida.getDate().toLocaleString());
            cargarTablas();
        }
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jtPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPedidosMouseClicked
        cargarProductos();
    }//GEN-LAST:event_jtPedidosMouseClicked

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        this.setVisible(false);
        new AdministradorLogueado().setVisible(true);
    }//GEN-LAST:event_jbBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MontosXMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MontosXMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MontosXMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MontosXMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MontosXMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcFechaElegida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbBack;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlMontoConsumido;
    private javax.swing.JLabel jlPedidosFecha;
    private javax.swing.JLabel jlProducto;
    private javax.swing.JLabel jlSeleccionFecha;
    private javax.swing.JTable jtMesas;
    private javax.swing.JTable jtPedidos;
    private javax.swing.JTable jtProductos;
    // End of variables declaration//GEN-END:variables
}
